=begin
#Selling Partner API for Pricing

#The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer information for Amazon Marketplace products.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ProductPricingApiModel::ConditionType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ConditionType' do
  before do
    # run before each test
    @instance = AmzSpApi::ProductPricingApiModel::ConditionType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ConditionType' do
    it 'should create an instance of ConditionType' do
      expect(@instance).to be_instance_of(AmzSpApi::ProductPricingApiModel::ConditionType)
    end
  end
end
