=begin
#Selling Partner API for Pricing

#The Selling Partner API for Pricing helps you programmatically retrieve product pricing and offer pricing information for Amazon Marketplace products.  For more information, see the [Product Pricing v2022-05-01 Use Case Guide](doc:product-pricing-api-v2022-05-01-use-case-guide).

The version of the OpenAPI document: 2022-05-01

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ProductPricingApiModel::HttpMethod
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::ProductPricingApiModel::HttpMethod do
  let(:instance) { AmzSpApi::ProductPricingApiModel::HttpMethod.new }

  describe 'test an instance of HttpMethod' do
    it 'should create an instance of HttpMethod' do
      expect(instance).to be_instance_of(AmzSpApi::ProductPricingApiModel::HttpMethod)
    end
  end
end
