=begin
#Selling Partner API for Sales

#The Selling Partner API for Sales provides APIs related to sales performance.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

module AmzSpApi::SalesApiModel
  VERSION = '0.1.0'
end
