=begin
#Selling Partner API for Sales

#The Selling Partner API for Sales provides APIs related to sales performance.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::SalesApiModel::GetOrderMetricsResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::SalesApiModel::GetOrderMetricsResponse do
  let(:instance) { AmzSpApi::SalesApiModel::GetOrderMetricsResponse.new }

  describe 'test an instance of GetOrderMetricsResponse' do
    it 'should create an instance of GetOrderMetricsResponse' do
      expect(instance).to be_instance_of(AmzSpApi::SalesApiModel::GetOrderMetricsResponse)
    end
  end
  describe 'test attribute "payload"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
