=begin
#Selling Partner API for Sales

#The Selling Partner API for Sales provides APIs related to sales performance.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::SalesApiModel::Money
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::SalesApiModel::Money do
  let(:instance) { AmzSpApi::SalesApiModel::Money.new }

  describe 'test an instance of Money' do
    it 'should create an instance of Money' do
      expect(instance).to be_instance_of(AmzSpApi::SalesApiModel::Money)
    end
  end
  describe 'test attribute "currency_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "amount"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
