=begin
#Selling Partner API for Finances

#The Selling Partner API for Finances helps you obtain financial information relevant to a seller's business. You can obtain financial events for a given order, financial event group, or date range without having to wait until a statement period closes. You can also obtain financial event groups for a given date range.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::FinancesApiModel::ListFinancialEventGroupsPayload
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::FinancesApiModel::ListFinancialEventGroupsPayload do
  let(:instance) { AmzSpApi::FinancesApiModel::ListFinancialEventGroupsPayload.new }

  describe 'test an instance of ListFinancialEventGroupsPayload' do
    it 'should create an instance of ListFinancialEventGroupsPayload' do
      expect(instance).to be_instance_of(AmzSpApi::FinancesApiModel::ListFinancialEventGroupsPayload)
    end
  end
  describe 'test attribute "next_token"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "financial_event_group_list"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
