=begin
#Selling Partner API for Merchant Fulfillment

#The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module AmzSpApi::MerchantFulfillmentApiModel
  class FileType
    APPLICATION_PDF = "application/pdf".freeze
    APPLICATION_ZPL = "application/zpl".freeze
    IMAGE_PNG = "image/png".freeze

    def self.all_vars
      @all_vars ||= [APPLICATION_PDF, APPLICATION_ZPL, IMAGE_PNG].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if FileType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #FileType"
    end
  end
end
