=begin
#Selling Partner API for Merchant Fulfillment

#The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module AmzSpApi::MerchantFulfillmentApiModel
  class StandardIdForLabel
    AMAZON_ORDER_ID = "AmazonOrderId".freeze

    def self.all_vars
      @all_vars ||= [AMAZON_ORDER_ID].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if StandardIdForLabel.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #StandardIdForLabel"
    end
  end
end
