=begin
#Selling Partner API for Direct Fulfillment Inventory Updates

#The Selling Partner API for Direct Fulfillment Inventory Updates provides programmatic access to a direct fulfillment vendor's inventory updates.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::VendorDirectFulfillmentInventoryApiModel::SubmitInventoryUpdateRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::VendorDirectFulfillmentInventoryApiModel::SubmitInventoryUpdateRequest do
  let(:instance) { AmzSpApi::VendorDirectFulfillmentInventoryApiModel::SubmitInventoryUpdateRequest.new }

  describe 'test an instance of SubmitInventoryUpdateRequest' do
    it 'should create an instance of SubmitInventoryUpdateRequest' do
      expect(instance).to be_instance_of(AmzSpApi::VendorDirectFulfillmentInventoryApiModel::SubmitInventoryUpdateRequest)
    end
  end
  describe 'test attribute "inventory"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
