=begin
#Selling Partner API for Fulfillment Inbound

#The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::FulfillmentInboundApiModel::PrepInstruction
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::FulfillmentInboundApiModel::PrepInstruction do
  let(:instance) { AmzSpApi::FulfillmentInboundApiModel::PrepInstruction.new }

  describe 'test an instance of PrepInstruction' do
    it 'should create an instance of PrepInstruction' do
      expect(instance).to be_instance_of(AmzSpApi::FulfillmentInboundApiModel::PrepInstruction)
    end
  end
end
