=begin
#Selling Partner API for Direct Fulfillment Shipping

#The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::VendorDirectFulfillmentShippingApiModel::GetShippingLabelResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::VendorDirectFulfillmentShippingApiModel::GetShippingLabelResponse do
  let(:instance) { AmzSpApi::VendorDirectFulfillmentShippingApiModel::GetShippingLabelResponse.new }

  describe 'test an instance of GetShippingLabelResponse' do
    it 'should create an instance of GetShippingLabelResponse' do
      expect(instance).to be_instance_of(AmzSpApi::VendorDirectFulfillmentShippingApiModel::GetShippingLabelResponse)
    end
  end
  describe 'test attribute "payload"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
