=begin
#Selling Partner API for Direct Fulfillment Shipping

#The Selling Partner API for Direct Fulfillment Shipping provides programmatic access to a direct fulfillment vendor's shipping data.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::VendorDirectFulfillmentShippingApiModel::TaxRegistrationDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::VendorDirectFulfillmentShippingApiModel::TaxRegistrationDetails do
  let(:instance) { AmzSpApi::VendorDirectFulfillmentShippingApiModel::TaxRegistrationDetails.new }

  describe 'test an instance of TaxRegistrationDetails' do
    it 'should create an instance of TaxRegistrationDetails' do
      expect(instance).to be_instance_of(AmzSpApi::VendorDirectFulfillmentShippingApiModel::TaxRegistrationDetails)
    end
  end
  describe 'test attribute "tax_registration_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["VAT", "GST"])
      # validator.allowable_values.each do |value|
      #   expect { instance.tax_registration_type = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "tax_registration_number"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "tax_registration_address"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "tax_registration_messages"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
