=begin
#Selling Partner API for Services

#With the Services API, you can build applications that help service providers get and modify their service orders and manage their resources.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ServicesApiModel::DayOfWeek
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::ServicesApiModel::DayOfWeek do
  let(:instance) { AmzSpApi::ServicesApiModel::DayOfWeek.new }

  describe 'test an instance of DayOfWeek' do
    it 'should create an instance of DayOfWeek' do
      expect(instance).to be_instance_of(AmzSpApi::ServicesApiModel::DayOfWeek)
    end
  end
end
