=begin
#Selling Partner API for Merchant Fulfillment

#The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::MerchantFulfillmentApiModel::InputTargetType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InputTargetType' do
  before do
    # run before each test
    @instance = AmzSpApi::MerchantFulfillmentApiModel::InputTargetType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InputTargetType' do
    it 'should create an instance of InputTargetType' do
      expect(@instance).to be_instance_of(AmzSpApi::MerchantFulfillmentApiModel::InputTargetType)
    end
  end
end
