=begin
#Selling Partner API for Merchant Fulfillment

#The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::MerchantFulfillmentApiModel::ShipmentStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::MerchantFulfillmentApiModel::ShipmentStatus do
  let(:instance) { AmzSpApi::MerchantFulfillmentApiModel::ShipmentStatus.new }

  describe 'test an instance of ShipmentStatus' do
    it 'should create an instance of ShipmentStatus' do
      expect(instance).to be_instance_of(AmzSpApi::MerchantFulfillmentApiModel::ShipmentStatus)
    end
  end
end
