=begin
#Selling Partner API for Shipment Invoicing

#The Selling Partner API for Shipment Invoicing helps you programmatically retrieve shipment invoice information in the Brazil marketplace for a selling partner’s Fulfillment by Amazon (FBA) orders.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ShipmentInvoicingApiModel::ShipmentInvoiceStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::ShipmentInvoicingApiModel::ShipmentInvoiceStatus do
  let(:instance) { AmzSpApi::ShipmentInvoicingApiModel::ShipmentInvoiceStatus.new }

  describe 'test an instance of ShipmentInvoiceStatus' do
    it 'should create an instance of ShipmentInvoiceStatus' do
      expect(instance).to be_instance_of(AmzSpApi::ShipmentInvoicingApiModel::ShipmentInvoiceStatus)
    end
  end
end
