=begin
#Selling Partner API for Uploads

#The Uploads API lets you upload files that you can programmatically access using other Selling Partner APIs, such as the A+ Content API and the Messaging API.

The version of the OpenAPI document: 2020-11-01

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

# Common files
require 'uploads-api-model/api_client'
require 'uploads-api-model/api_error'
require 'uploads-api-model/version'
require 'uploads-api-model/configuration'

# Models
require 'uploads-api-model/models/create_upload_destination_response'
require 'uploads-api-model/models/error'
require 'uploads-api-model/models/upload_destination'

# APIs
require 'uploads-api-model/api/uploads_api'

module AmzSpApi::UploadsApiModel
  class << self
    # Customize default settings for the SDK using block.
    #   AmzSpApi::UploadsApiModel.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
