=begin
#Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data

#The Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data provides programmatic access to vendor direct fulfillment sandbox test data.

The version of the OpenAPI document: 2021-10-28

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

module AmzSpApi::VendorDirectFulfillmentSandboxTestDataApiModel
  VERSION = '0.1.0'
end
