=begin
#Selling Partner API for Listings Restrictions

#The Selling Partner API for Listings Restrictions provides programmatic access to restrictions on Amazon catalog listings.  For more information, see the [Listings Restrictions API Use Case Guide](doc:listings-restrictions-api-v2021-08-01-use-case-guide).

The version of the OpenAPI document: 2021-08-01

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ListingsRestrictionsApiModel::Reason
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::ListingsRestrictionsApiModel::Reason do
  let(:instance) { AmzSpApi::ListingsRestrictionsApiModel::Reason.new }

  describe 'test an instance of Reason' do
    it 'should create an instance of Reason' do
      expect(instance).to be_instance_of(AmzSpApi::ListingsRestrictionsApiModel::Reason)
    end
  end
  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "reason_code"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["APPROVAL_REQUIRED", "ASIN_NOT_FOUND", "NOT_ELIGIBLE"])
      # validator.allowable_values.each do |value|
      #   expect { instance.reason_code = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "links"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
