=begin
#Selling Partner API for Product Fees

#The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module AmzSpApi::ProductFeesApiModel
  class IdType
    ASIN = "ASIN".freeze
    SELLER_SKU = "SellerSKU".freeze

    def self.all_vars
      @all_vars ||= [ASIN, SELLER_SKU].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if IdType.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #IdType"
    end
  end
end
