=begin
#Selling Partner API for FBA Inventory

#The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::FbaInventoryApiModel::ResearchingQuantity
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::FbaInventoryApiModel::ResearchingQuantity do
  let(:instance) { AmzSpApi::FbaInventoryApiModel::ResearchingQuantity.new }

  describe 'test an instance of ResearchingQuantity' do
    it 'should create an instance of ResearchingQuantity' do
      expect(instance).to be_instance_of(AmzSpApi::FbaInventoryApiModel::ResearchingQuantity)
    end
  end
  describe 'test attribute "total_researching_quantity"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "researching_quantity_breakdown"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
