=begin
#Selling Partner APIs for Fulfillment Outbound

#The Selling Partner API for Fulfillment Outbound lets you create applications that help a seller fulfill Multi-Channel Fulfillment orders using their inventory in Amazon's fulfillment network. You can get information on both potential and existing fulfillment orders.

The version of the OpenAPI document: 2020-07-01

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'date'

module AmzSpApi::FulfillmentOutboundApiModel
  class CurrentStatus
    IN_TRANSIT = "IN_TRANSIT".freeze
    DELIVERED = "DELIVERED".freeze
    RETURNING = "RETURNING".freeze
    RETURNED = "RETURNED".freeze
    UNDELIVERABLE = "UNDELIVERABLE".freeze
    DELAYED = "DELAYED".freeze
    AVAILABLE_FOR_PICKUP = "AVAILABLE_FOR_PICKUP".freeze
    CUSTOMER_ACTION = "CUSTOMER_ACTION".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = CurrentStatus.constants.select { |c| CurrentStatus::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #CurrentStatus" if constantValues.empty?
      value
    end
  end
end
