=begin
#Selling Partner API for Fulfillment Inbound

#The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module AmzSpApi::FulfillmentInboundApiModel
  class BarcodeInstruction
    REQUIRES_FNSKU_LABEL = "RequiresFNSKULabel".freeze
    CAN_USE_ORIGINAL_BARCODE = "CanUseOriginalBarcode".freeze
    MUST_PROVIDE_SELLER_SKU = "MustProvideSellerSKU".freeze

    def self.all_vars
      @all_vars ||= [REQUIRES_FNSKU_LABEL, CAN_USE_ORIGINAL_BARCODE, MUST_PROVIDE_SELLER_SKU].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if BarcodeInstruction.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #BarcodeInstruction"
    end
  end
end
