=begin
#Selling Partner API for Fulfillment Inbound

#The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module AmzSpApi::FulfillmentInboundApiModel
  class PackageStatus
    SHIPPED = "SHIPPED".freeze
    IN_TRANSIT = "IN_TRANSIT".freeze
    DELIVERED = "DELIVERED".freeze
    CHECKED_IN = "CHECKED_IN".freeze
    RECEIVING = "RECEIVING".freeze
    CLOSED = "CLOSED".freeze
    DELETED = "DELETED".freeze

    def self.all_vars
      @all_vars ||= [SHIPPED, IN_TRANSIT, DELIVERED, CHECKED_IN, RECEIVING, CLOSED, DELETED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if PackageStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #PackageStatus"
    end
  end
end
