=begin
#Selling Partner API for Fulfillment Inbound

#The Selling Partner API for Fulfillment Inbound lets you create applications that create and update inbound shipments of inventory to Amazon's fulfillment network.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'date'
require 'time'

module AmzSpApi::FulfillmentInboundApiModel
  class UnitOfWeight
    POUNDS = "pounds".freeze
    KILOGRAMS = "kilograms".freeze

    def self.all_vars
      @all_vars ||= [POUNDS, KILOGRAMS].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if UnitOfWeight.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #UnitOfWeight"
    end
  end
end
