=begin
#Selling Partner API for Reports

#The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.

The version of the OpenAPI document: 2021-06-30

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ReportsApiModel::CreateReportScheduleResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::ReportsApiModel::CreateReportScheduleResponse do
  let(:instance) { AmzSpApi::ReportsApiModel::CreateReportScheduleResponse.new }

  describe 'test an instance of CreateReportScheduleResponse' do
    it 'should create an instance of CreateReportScheduleResponse' do
      expect(instance).to be_instance_of(AmzSpApi::ReportsApiModel::CreateReportScheduleResponse)
    end
  end
  describe 'test attribute "report_schedule_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
