=begin
#Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data

#The Selling Partner API for Vendor Direct Fulfillment Sandbox Test Data provides programmatic access to vendor direct fulfillment sandbox test data.

The version of the OpenAPI document: 2021-10-28

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::VendorDirectFulfillmentSandboxTestDataApiModel::TestCaseData
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::VendorDirectFulfillmentSandboxTestDataApiModel::TestCaseData do
  let(:instance) { AmzSpApi::VendorDirectFulfillmentSandboxTestDataApiModel::TestCaseData.new }

  describe 'test an instance of TestCaseData' do
    it 'should create an instance of TestCaseData' do
      expect(instance).to be_instance_of(AmzSpApi::VendorDirectFulfillmentSandboxTestDataApiModel::TestCaseData)
    end
  end
  describe 'test attribute "scenarios"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
