=begin
#Selling Partner API for Product Fees

#The Selling Partner API for Product Fees lets you programmatically retrieve estimated fees for a product. You can then account for those fees in your pricing.

The version of the OpenAPI document: v0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.5.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::ProductFeesApiModel::FeesEstimateByIdRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::ProductFeesApiModel::FeesEstimateByIdRequest do
  let(:instance) { AmzSpApi::ProductFeesApiModel::FeesEstimateByIdRequest.new }

  describe 'test an instance of FeesEstimateByIdRequest' do
    it 'should create an instance of FeesEstimateByIdRequest' do
      expect(instance).to be_instance_of(AmzSpApi::ProductFeesApiModel::FeesEstimateByIdRequest)
    end
  end
  describe 'test attribute "fees_estimate_request"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "id_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "id_value"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
