=begin
#Selling Partner API for Feeds

#The Selling Partner API for Feeds lets you upload data to Amazon on behalf of a selling partner.

The version of the OpenAPI document: 2021-06-30

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for AmzSpApi::FeedsApiModel::ErrorList
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe AmzSpApi::FeedsApiModel::ErrorList do
  let(:instance) { AmzSpApi::FeedsApiModel::ErrorList.new }

  describe 'test an instance of ErrorList' do
    it 'should create an instance of ErrorList' do
      expect(instance).to be_instance_of(AmzSpApi::FeedsApiModel::ErrorList)
    end
  end
  describe 'test attribute "errors"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
